### ISSUE TITLE
Documentation: Refactoring of the README

### ISSUE THREAD

**Issue by Pietfried** [EVerest/libocpp#842]
### OCPP Version

OCPP1.6, OCPP2.0.1

### Describe the problem

The current README is very bloated and partly contains information that we plan to move to other parts of libocpp.

### Describe your solution

We decided to not merge the structure proposed in We decided to not merge the structure proposed in https://github.com/EVerest/libocpp/pull/836 but to accept certain parts of it as part of a seperate PR that refactors the README.

The goal of this issue is to reduce the README and to seperate better between user and developer documentation.

These are the notes for how to modify the README that were discussed in the cloud WG F2F meeting
* Include Generic introduction
* Include Supported functionality / feature profiles
* Include CSMS compatability
* Include Integration in EVerest
* Reduce section "Integrate this library" and move to developer documentation
* Remove section "Install libocpp" -> Add Requirements for the library instead; Building and installing should be moved to developer documentation
* Remove section "Quickstart" --> Link to EVerest SIL instead
* Remove section "Building doxygen documentation" to developer documentation
* Remove section "Unit testing": Move to developer documentation
* Remove section "Building with FetchContent": Move to developer documentation
* Remove section "Support for security profile 2 and 3 with TPM" Move to developer documentation

### TODOs

- [x] Split up docs/ folder into docs/v16/ docs/v201/ and docs/common or docs/general
- [x] Review https://github.com/EVerest/libocpp/pull/836 and include parts in the refactoring PR
- [x] Reduce README file using the details above
- [x] Move removed parts of the README to the new developer documentation section

**Comment by Pietfried** [comment]
Completed
